ckpt_intvl: 1000
summ_image_count: 8

phase_param:
  train:
    data_filenames:
      - train.tfrecord
    data_slots: 7
    num_slots: 8
  valid:
    data_filenames:
      - valid.tfrecord
    data_slots: 7
    num_slots: 8
  test:
    data_filenames:
      - test.tfrecord
    data_slots: 7
    num_slots: 8
  general:
    data_filenames:
      - general.tfrecord
    data_slots: 11
    num_slots: 12

lr: 4.0e-4
lr_decay: 0.5
decay_steps: 100000
warmup_steps: 10000
data_cache: true
data_shuffle: 50000
batch_size: 64
num_parallel: 1
num_steps: 500000
num_tests: 5
seg_overlap: true
image_shape: [128, 128, 3]

slot_steps: 3
slot_size: 64

enc_filters: [64, 64, 64, 64]
enc_kernels: [5, 5, 5, 5]
enc_strides: [1, 1, 1, 1]
enc_main_units: [64, 64]
enc_slot_units: [128]

dec_filters: [64, 64, 64, 64, 64]
dec_kernels: [5, 5, 5, 5, 5, 3]
dec_strides: [2, 2, 2, 2, 1, 1]
