ckpt_intvl: 1000
summ_image_count: 8

phase_param:
  train:
    num_slots: 8
  valid:
    num_slots: 8
  test:
    num_slots: 8
  general:
    num_slots: 12

loss_coef:
  temp:
    step: []
    value: [10.0, 0.5]
    linear: [false]
  bck_prior:
    step: [25000]
    value: [0.2, 0.0, 0.0]
    linear: [true, true]

normal_scale: 0.3
lr: 2.0e-4
batch_size: 64
num_steps: 200000
num_tests: 5
seg_overlap: true

enc_back_channel: [4, 4, 8, 8, 16, 16]
enc_back_kernel: [3, 3, 3, 3, 3, 3]
enc_back_stride: [1, 2, 1, 2, 1, 2]
enc_back_hidden: [256]
latent_back_size: 8
dec_back_avg_hidden_rev: [32, 32]
dec_back_res_channel_rev: [8, 8, 16, 16, 32, 32]
dec_back_res_kernel_rev: [3, 3, 3, 3, 3, 3]
dec_back_res_stride_rev: [1, 2, 1, 2, 1, 2]
dec_back_res_hidden_rev: [256]

upd_channel: [8, 8, 16, 16, 32, 32]
upd_kernel: [3, 3, 3, 3, 3, 3]
upd_stride: [1, 2, 1, 2, 1, 2]
upd_hidden: [256]
state_size: 256

prior_pres_alpha: 1.0e-2
enc_pres_hidden: [256, 256]

prior_where_mu: [-0.5, -0.5, 0.0, 0.0]
prior_where_std: [0.5, 0.5, 0.5, 0.5]
enc_where_hidden: [256, 256]

enc_what_channel: [8, 8, 16, 16, 32, 32]
enc_what_kernel: [3, 3, 3, 3, 3, 3]
enc_what_stride: [1, 2, 1, 2, 1, 2]
enc_what_hidden: [256]
latent_what_size: 64
dec_what_channel_rev: [8, 8, 16, 16, 32, 32]
dec_what_kernel_rev: [3, 3, 3, 3, 3, 3]
dec_what_stride_rev: [1, 2, 1, 2, 1, 2]
dec_what_hidden_rev: [256]
