ckpt_intvl: 1000
summ_image_count: 8

phase_param:
  train:
    data_filenames:
      - train.tfrecord
    data_slots: 6
    num_slots: 7
  valid:
    data_filenames:
      - valid.tfrecord
    data_slots: 6
    num_slots: 7
  test:
    data_filenames:
      - test.tfrecord
    data_slots: 6
    num_slots: 7
  general:
    data_filenames:
      - general.tfrecord
    data_slots: 9
    num_slots: 10

loss_coef:
  nll:
    step: []
    value: [1.0, 1.0]
    linear: [true]
  kld:
    step: []
    value: [0.5, 0.5]
    linear: [true]
  mask:
    step: []
    value: [0.5, 0.5]
    linear: [true]

normal_scale:
  bck: 0.09
  obj: 0.11
lr: 1.0e-4
data_layers: false
data_cache: true
data_shuffle: 60000
batch_size: 64
batch_size_valid: 100
num_parallel: 8
num_steps: 1000000
num_tests: 5
image_shape: [64, 64, 3]
seg_overlap: true

att_channel: [32, 32, 64, 64, 64]
att_kernel: [3, 3, 3, 3, 3]
att_stride: [2, 2, 2, 2, 1]
att_hidden: [128, 128]

enc_channel: [32, 32, 64, 64]
enc_kernel: [3, 3, 3, 3]
enc_stride: [2, 2, 2, 2]
enc_hidden: [256]
latent_size: 16
dec_channel: [32, 32, 32, 32]
dec_kernel: [3, 3, 3, 3]
dec_shape: [72, 70, 68, 66]
