image_height: 64
image_width: 64
train:
  num_data: 50000
  num_objects: [2, 3, 4]
  range_scale: [1.0, 1.5]
  min_visible: 0.25
valid:
  num_data: 1000
  num_objects: [2, 3, 4]
  range_scale: [1.0, 1.5]
  min_visible: 0.25
test:
  num_data: 1000
  num_objects: [2, 3, 4]
  range_scale: [1.0, 1.5]
  min_visible: 0.25
general:
  num_data: 1000
  num_objects: [5, 6]
  range_scale: [1.0, 1.5]
  min_visible: 0.25
