ckpt_intvl: 1000
summ_image_count: 8

phase_param:
  train:
    data_filenames:
      - train.tfrecord
    data_slots: 7
    num_slots: 8
    num_iters: 5
    iter_wt: null
  valid:
    data_filenames:
      - valid.tfrecord
    data_slots: 7
    num_slots: 8
    num_iters: 5
    iter_wt: null
  test:
    data_filenames:
      - test.tfrecord
    data_slots: 7
    num_slots: 8
    num_iters: 5
    iter_wt: null
  general:
    data_filenames:
      - general.tfrecord
    data_slots: 11
    num_slots: 12
    num_iters: 5
    iter_wt: null

normal_scale: 0.1
lr: 3.0e-4
clip_norm: 5.0
data_layers: false
data_cache: true
data_shuffle: 60000
batch_size: 32
batch_size_valid: 100
num_parallel: 8
num_steps: 1000000
num_tests: 5
image_shape: [128, 128, 3]
seg_overlap: true

upd_channel: [64, 64, 64, 64]
upd_kernel: [3, 3, 3, 3]
upd_stride: [2, 2, 2, 2]
upd_hidden: [256]
state_size: 256
latent_size: 64
dec_channel: [64, 64, 64, 64]
dec_kernel: [3, 3, 3, 3, 3]
dec_shape: [128, 128, 128, 128]
